### ISSUE TITLE
How does migration work?

### ISSUE THREAD

**Issue by Mark-Kiss** [event-engine/php-engine#28]
Hi, 

I was wondering, couldn't find it in the docs: how state/docStore migration works?
Let's say I add a new required property: how would you make sure, that the persisted states/models in the system will get updated as well? 
Do you have a best practice/example somewhere?

**Comment by codeliner** [comment]
Hi,

sorry for answering late. If you add a new required property you have two choices:

1.) Write a script to update state in the database and execute it after deployment.
2.) Initialize the new property with a default in the state class (ImmutableRecord). How that works is described here: https://event-engine.io/api/immutable_state.html#3-4-5-4

Option 2 is our favorite, because option 1 might require two deployments to not break production during the time the new code is deployed but the update script not executed.

**Comment by Mark-Kiss** [comment]
Thanks for the reply!
